### ISSUE TITLE
应用安装：安装应用成功后，引导用户进行下一步操作

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#113]
应用安装：安装应用成功后，引导用户进行下一步操作。
下一步操作有3种可能：
1） 将此应用及安装到其他网关，点击后，用户选择网关列表。
2） 继续对目前操作的网关安装其他应用，点击后，页面进入应用安装选择页面
3） 结束应用安装，点击后，页面进入当前网关的应用列表。

**Comment by srdgame** [comment]
已经增加了引导页面
