### ISSUE TITLE
设备列表：数据表格优先保证名称，时间戳的完整显示，最小宽度需求，同时表格可以最大化铺满窗口

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#141]
数据表格优先保证名称，时间戳的完整显示，最小宽度需求，同时表格可以最大化铺满窗口。
![image](https://user-images.githubusercontent.com/11530494/59166949-393e8d00-8b61-11e9-826a-da180d8082aa.png)

**Comment by srdgame** [comment]
已经设置为固定宽度，应该没有这个问题了
