### ISSUE TITLE
设备列表，应用列表，日志表格等可展开二级表格的行样式增加“手型”鼠标样式。

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#142]
设备列表，应用列表，日志表格等可展开二级表格的行样式增加“手型”鼠标样式。

![image](https://user-images.githubusercontent.com/11530494/59167088-05b03280-8b62-11e9-80cf-c946b78b7980.png)

**Comment by srdgame** [comment]
closed.
