### ISSUE TITLE
网关日志：日志表格中日志显示不全

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#145]
网关日志：日志表格中日志显示不全
![image](https://user-images.githubusercontent.com/11530494/59174895-d3b0c780-8b85-11e9-8989-01c71a5c70cd.png)

**Comment by ai-cuicui** [comment]
![image](https://user-images.githubusercontent.com/36217841/60167890-93647100-9836-11e9-8ccf-32c9915eccc6.png)
