### ISSUE TITLE
代码编辑：代码保存按钮不可用

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#152]
代码编辑：代码保存按钮不可用

![image](https://user-images.githubusercontent.com/11530494/59189662-441f0f00-8bad-11e9-96f9-9e9fab9435f7.png)

**Comment by ai-cuicui** [comment]
1已有自动保存（延时三秒），删除切换文件保存提示框，
2若在三秒内修改以及切换文件，切换页面时进行保存
