### ISSUE TITLE
应用配置：配置修改后，再次打开应用配置，配置不见了。

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#157]
应用配置：配置修改成后，再次打开应用配置，配置不见了。

![image](https://user-images.githubusercontent.com/11530494/59253874-b7825880-8c61-11e9-8064-9dfc335a1c56.png)

![image](https://user-images.githubusercontent.com/11530494/59253969-e698ca00-8c61-11e9-9e5e-67b11488bc69.png)

**Comment by viccom** [comment]
支持配置面板的无此问题，不支持配置面板存在问题，

**Comment by srdgame** [comment]
fixed
