### ISSUE TITLE
应用安装：安装应用时，实例名中间存在不可见字符，应用可安装，无法启动

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#170]
安装应用时，实例名中间存在不可见字符，应用可安装，无法启动

![image](https://user-images.githubusercontent.com/11530494/59320157-df27fe00-8cff-11e9-81f7-a1cf3cdcec09.png)

**Comment by srdgame** [comment]
已经修复，限制了应用名称可使用的范围 ( 大小写字母和下划线）
