### ISSUE TITLE
应用列表：应该更改名称后导致应用停止

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#172]
应用列表：应该更改名称后导致应用停止
改名前
![image](https://user-images.githubusercontent.com/11530494/59322994-5fa02c00-8d0b-11e9-994a-45f650683855.png)

改名后，实际上并未改名，还是原来的实例名提交的。
![image](https://user-images.githubusercontent.com/11530494/59323015-7050a200-8d0b-11e9-814b-975594bd07f3.png)

**Comment by srdgame** [comment]
Bug of freeioe. will be fixed soon

**Comment by srdgame** [comment]
FreeIOE 版本1182修复此问题
