### ISSUE TITLE
Dashboard: 自适应不完整

### ISSUE THREAD

**Issue by srdgame** [thingsroot/ReactProject#18]
当浏览器窗口大小变化的时候，图表并没有跟随大小变化

**Comment by srdgame** [comment]
不更改浏览器大小，切换事件列表也出现自适应问题

![图片](https://user-images.githubusercontent.com/54447/57193402-44ecd180-6f6d-11e9-86b4-16c4e05f87b9.png)

**Comment by srdgame** [comment]
事件列表的高度计算在我的浏览器里面有问题,导致出现自适应不完成.

**Comment by ai-cuicui** [comment]
已修改
