### ISSUE TITLE
网关中的平台事件：点击某一条记录时页面崩溃

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#182]
网关中的平台事件：点击某一条记录时页面崩溃
点击前
![image](https://user-images.githubusercontent.com/11530494/59478199-0eb74180-8e8b-11e9-8e76-33544b207a2d.png)
点击后
![image](https://user-images.githubusercontent.com/11530494/59478207-1a0a6d00-8e8b-11e9-8801-ea60de121aba.png)

**Comment by srdgame** [comment]
已修复，保持和设备事件同等的行为模式
