### ISSUE TITLE
应用安装：安装时应用能启动开机自启为打开状态，安装时应用不能启动开机自启为打开状态，

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#185]
应用安装：安装时应用能启动开机自启为打开状态，安装时应用不能启动开机自启为打开状态，
希望的情况时，应用被安装，无论此应用安装时时候能正常启动，开机自启这个选项应该是允许

**Comment by srdgame** [comment]
安装不成功，开启开机自启的话，会导致应用不停的启动-》失败=》启动=》失败的循环。 所以当前行为是正确的。
