### ISSUE TITLE
应用设置：格式显示有问题

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#193]
在编辑态时：
![image](https://user-images.githubusercontent.com/11530494/59731602-68e44800-9279-11e9-9620-a15a8a3cd3c3.png)

在浏览态时：
![image](https://user-images.githubusercontent.com/11530494/59731622-7bf71800-9279-11e9-84ce-49ca54b1d6c2.png)

使用其他工具浏览markdown格式时
![image](https://user-images.githubusercontent.com/11530494/59731655-a0eb8b00-9279-11e9-8f4b-c4ded89b0ac3.png)

**Comment by ai-cuicui** [comment]
https://simplemde.com/markdown-guide
