### ISSUE TITLE
网关列表：点击某个网关查看后，点击chrome的返回键，布局出现问题

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#194]
正常看到的网关列表应该是这样：
![image](https://user-images.githubusercontent.com/11530494/59731736-f1fb7f00-9279-11e9-8a1f-93f0c76245b6.png)

从网关列表中选择某个网关查看设备数据后，点击浏览器的返回键，出现下面的页面布局
![image](https://user-images.githubusercontent.com/11530494/59731757-0770a900-927a-11e9-926f-dce71f2c45ab.png)

从网关列表中选择某个网关查看网关属性后，点击浏览器的返回键，出现下面的页面布局
![image](https://user-images.githubusercontent.com/11530494/59731783-1ce5d300-927a-11e9-90de-5c6340e53040.png)

**Comment by srdgame** [comment]
antd Divider 存在问题，使用span代替 divider..    @a980263316
