### ISSUE TITLE
应用设置：应用ID字符检测提示不准确

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#200]
应用设置：应用ID字符检测规则不合适
![image](https://user-images.githubusercontent.com/11530494/59994672-5443ed80-9687-11e9-8fd2-e0c337298d16.png)

**Comment by ai-cuicui** [comment]
已修改为只能全是字母

**Comment by ai-cuicui** [comment]
已修改为应用ID 不含中文，文本框只能输入非中文内容
