### ISSUE TITLE
应用安装面板：宽度不够，导致文字换行

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#206]
应用安装面板：存在最小宽度，导致文字换行
![image](https://user-images.githubusercontent.com/11530494/60071974-971cc880-974e-11e9-8075-2d74a8d3e6a1.png)

**Comment by ai-cuicui** [comment]
![image](https://user-images.githubusercontent.com/36217841/60156456-2abdca00-981f-11e9-9c71-506bf463d5dd.png)
