### ISSUE TITLE
登录：周期检测用户登录是否失效

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#21]
用户登录浏览页面一段时间后，关闭页面或者关闭浏览器了。过一段时间后，再次打开页面，页面还能打开，但实际上用户会话已经过期。
因此需要在用户打开页面时检测会话是否有效，若已失效，则跳转登录页面，如有效用户打开的URL是登录URL，注册URL，找回密码URL，则自动跳转到HOME页。

**Comment by srdgame** [comment]
![图片](https://user-images.githubusercontent.com/54447/57566601-31c08280-7401-11e9-8b97-07a06213a055.png)

**Comment by a980263316** [comment]
Fixed with  commit ce05cd9acb9a5435268fe31df118943ede856a77
