### ISSUE TITLE
我的应用：安装到网关：按钮一直存在，点击时先选择目标网关

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#211]
我的应用：安装到网关：按钮一直存在，点击时先选择目标网关
![image](https://user-images.githubusercontent.com/11530494/60316609-d0974300-999d-11e9-9bc5-926f50b73273.png)

**Comment by srdgame** [comment]
需要考虑如何设计交互的问题。

**Comment by a980263316** [comment]
Fixed with commit f49d185f3ad307b3085a0d4e2c5fecb9ab9d0c98
