### ISSUE TITLE
用户登录：登录提示修改

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#232]
1. 用户打开登录页面时，登录页面的用户输入框提示使用中文，背景提示文字“邮件地址或用户名”，密码输入框提示使用中文，背景提示文字“密码”。
目前页面如下：
![image](https://user-images.githubusercontent.com/11530494/64411979-02750600-d0c1-11e9-9f4c-1645b0510986.png)

2. 用户登录失败时，明确反馈信息给用户；是用户未注册或者用户被禁用，还是密码错误。

**Comment by a980263316** [comment]
Fixed with commit a41f83073309800195f08ef5fdc43a214d6f4ae5
