### ISSUE TITLE
网关列表：网关处于非在线状态时无法删除

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#233]
网关列表：网关处于非在线状态时无法删除，应该时可以删除的（从用户名下移除）
![image](https://user-images.githubusercontent.com/11530494/64577989-9e985900-d3b0-11e9-8b40-3ed8673dd665.png)

**Comment by a980263316** [comment]
Fixed with commit c5e4f705b9572d27e1e0a5b0c323e978f5dfd32c
