### ISSUE TITLE
应用详情：应用不属于当前用户时，不能显示删除按钮

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#236]
应用详情：应用不属于当前用户时，不能显示删除按钮
![image](https://user-images.githubusercontent.com/11530494/65296877-8686bd80-db98-11e9-9aec-660ae4806640.png)

**Comment by a980263316** [comment]
Fixed with commit 88c907cb439be7ed2ec613b69dd8f11e8a2b112f
