### ISSUE TITLE
扩展功能：将专用网关页面中的网络配置页面移到通用版本中

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#240]
通用版本中可开启网络配置功能。
![image](https://user-images.githubusercontent.com/11530494/68726248-d3689c80-05fb-11ea-8315-b6addfbf9db6.png)
开启网络配置功能后可查看网关的网络配置信息，及修改LAN接口的IP地址
![image](https://user-images.githubusercontent.com/11530494/68726274-e7140300-05fb-11ea-98d0-976ef3803726.png)

**Comment by a980263316** [comment]
Fixed with commit 738173ebba73a727c3121164ff217cc0b645e12a
