### ISSUE TITLE
扩展功能：远程编程-网络页面布局及样式微小调整

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#241]
页面调整后的效果图如下：
![image](https://user-images.githubusercontent.com/11530494/68726443-6efa0d00-05fc-11ea-9ca1-9f3b5492bb84.png)

页面下方增加一个消息区域，用来显示远程编程服务启动或停止时后台反馈的信息。

**Comment by a980263316** [comment]
Fixed with commit 738173ebba73a727c3121164ff217cc0b645e12a
