### ISSUE TITLE
扩展功能：远程编程-网络页面中启动服务时的逻辑调整

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#243]
启动虚拟网络由如下两部组成：
1. 给本地后台程序发出启动虚拟网络相关服务的指令。
2. 让本地后台程给远程网关下发启动虚拟网络相关服务的指令。

前端页面在处理这个流程时，第1步和第2步之间不要使用setTimeout这种方式，而需要等待本地后台程序执行第1步的返回结果（等待时间最长可以为10秒），如后台程序返回的"payload"的 "result"是True时则进行第2步，如"result"是False，就不用再进行第2步了，表明本次任务失败了。
任务一旦开始，启动按钮就不能点击，而且提示目前正在任务中。任务执行结果返回（第1步失败则整个任务也就执行失败，如执行了第2步，任务成功还是失败也是看返回值）才能报告这次任务执行时成功还是失败。

**Comment by a980263316** [comment]
Fixed with commit 738173ebba73a727c3121164ff217cc0b645e12a
