### ISSUE TITLE
模版克隆：无法克隆成功

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#259]
模版克隆：无法克隆成功

![image](https://user-images.githubusercontent.com/11530494/70809245-56983080-1dfc-11ea-9289-f9575b3977a0.png)

**Comment by a980263316** [comment]
Fixed with commit 32139e7e06f522b1b6e47b705844c8fc869b9a39

**Comment by a980263316** [comment]
Fixed with commit 32139e7e06f522b1b6e47b705844c8fc869b9a39
