### ISSUE TITLE
应用列表：需求调整

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#26]
1） 应用列表改为表格展开效果，即进入页面时应用列表为收缩效果，应用前面有+图标。
2） 点击+图标，应用展开，出现应用详情，可查看应用的详情信息，可对应用进行启/停/升级/卸载/在线编辑/参数配置，可监视应用的运行日志和报文。

**Comment by srdgame** [comment]
@a980263316 目前的信息差不多了，布局需要调整一下
