### ISSUE TITLE
企业：成员管理：非企业管理员看不见成员管理菜单

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#268]
企业：成员管理：非企业管理员看不见成员管理菜单

![image](https://user-images.githubusercontent.com/11530494/71649484-246a5680-2d4a-11ea-85f8-e4d99de59d6b.png)

**Comment by a980263316** [comment]
Fixed with commit 17d24c1efaee618138fb21335cd51563cc64c8aa
