### ISSUE TITLE
设备模板的一些改进

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#291]
1. 目前编辑按钮没什么作用，去掉。
![image](https://user-images.githubusercontent.com/11530494/72411673-6497f300-37a6-11ea-8283-3939cbe0804f.png)

2. 在操作一列增加一个“升级最新”按钮，当设备模板存在比当前选择更新的版本时，“升级最新”按钮可点击，将版本更新为最新的版本号。

3. 选择模板面板中，所有的设备模板都支持克隆按钮。
![image](https://user-images.githubusercontent.com/11530494/72411826-cf492e80-37a6-11ea-810b-b094e40d1f31.png)

4. 选择模板面板中，刷新按钮无作用，及无法刷新出新增加的设备模板，也无法刷新设备模板版本已经更新的版本号。

**Comment by a980263316** [comment]
Fixed with commit 366334df7dc2873ea49794344d7ffcd476f664eb
