### ISSUE TITLE
应用安装:如应用不支持配置面板,则默认显示"JSON源码"页面

### ISSUE THREAD

**Issue by srdgame** [thingsroot/ReactProject#32]
另外把JSON源码改为:配置信息

**Comment by ai-cuicui** [comment]
已修改，暂时未能提交

**Comment by srdgame** [comment]
Fixed with commit ce05cd9acb9a5435268fe31df118943ede856a77

**Comment by srdgame** [comment]
最新代码没有这个功能，reopen

**Comment by srdgame** [comment]
明天给我演示一下，你修复的结果，再关闭这个。 我这里还是没有实现我的要求
