### ISSUE TITLE
网关应用列表可展开

### ISSUE THREAD

**Issue by a980263316** [thingsroot/ReactProject#44]
在展开下添加操作按钮，将删除、配置、启停、更新版本、更改名称挪到展开内的页面，未展开前不显示开机自启以及设备删除，

**Comment by srdgame** [comment]
保持和设备列表一样的点击展开的行为模式，而不是只有点击前面的+号展开应用

**Comment by srdgame** [comment]
展开后的信息目前太单薄，需要补充一些信息，而不是只是显示那些操作按钮。
补充的信息可以包含：应用名称（应用商店名称），应用开发者....

按钮方面更新应用应有提示最新版本号显示，
操作按钮布局方面现在这种平均分布是不合适的。 靠右，有固定间隔的分布

**Comment by srdgame** [comment]
应用启动、停止、重启  三个按钮不要做自动切换，保持一直可用的状态就可以。

**Comment by srdgame** [comment]
如没有新版本，将“更新应用”按钮置为不可用状态

**Comment by srdgame** [comment]
@a980263316

**Comment by a980263316** [comment]
Fiexd with commit ae338ae5131c95acde3effc9161ff99750901dd1
