### ISSUE TITLE
平台消息&设备消息：确定动作靠左，过滤条件靠右

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#59]
![image](https://user-images.githubusercontent.com/11530494/57674160-003df600-7651-11e9-92b4-7afb661de810.png)
目前的排列方式是 过滤条件|动作|过滤。将动作按钮靠左放，过滤靠右
“确认消息”|“确认所有消息”                                                       过滤条件1 过滤条件2过滤条件3……

**Comment by srdgame** [comment]
过滤条件都是 right float央视，左边只有“确认消息”“确认所有消息”两个按钮.

现在“消息类型”“记录数”“时间”仅仅是“排在动作按钮的右边”， 而不是“靠右显示”
