### ISSUE TITLE
平台消息&设备消息：缺少“确认消息”/“未确认消息”/“全部消息”过滤

### ISSUE THREAD

**Issue by viccom** [thingsroot/ReactProject#64]
缺少“确认消息”/“未确认消息”/“全部消息”过滤

**Comment by viccom** [comment]
增加issues的标签

**Comment by srdgame** [comment]
代码未提交？ @ai-cuicui

**Comment by ai-cuicui** [comment]
![image](https://user-images.githubusercontent.com/36217841/57840918-1e942500-77fc-11e9-828f-d262653b30ee.png)
