### ISSUE TITLE
应用信息修改：完成后不要这么快速跳转，也应跳转回应用信息页面而不是我的应用页面

### ISSUE THREAD

**Issue by srdgame** [thingsroot/ReactProject#77]
完成后不要这么快速跳转，快速跳转的结果是用户根本没看到成功提示信息，感觉是页面发生意外进行了跳转一样的感觉。

同时应跳转回应用信息页面而不是我的应用页面。

**Comment by ai-cuicui** [comment]
已添加定时器，并修改回退
