### ISSUE TITLE
我的网关：更改网管名称描述弹窗，增加所有者选项

### ISSUE THREAD

**Issue by srdgame** [thingsroot/ReactProject#87]
目前的没有所有者选项，而且会自动将设备的所有者更改为公司设备（当设备为个人设备时）

修改：
1。 增加所有者选项（增加网关按钮的弹窗也增加这个选项）
2。 菜单名称从“更改名称和经纬度”改为“网关属性”

**Comment by srdgame** [comment]
把添加ThingsLink改为添加网关

**Comment by a980263316** [comment]
Fixed with commit 281d4a51d6cd7ec0678b39cc9c7bee85db6748ee
