### ISSUE TITLE
网关详情：当从其他页面返回日志页面时，日志并不刷新

### ISSUE THREAD

**Issue by srdgame** [thingsroot/ReactProject#90]
只有触发滚动条后，才会有刷新。

**Comment by srdgame** [comment]
http://localhost:3000/mygatesdevices/EFC43C54-6A34-11E8-8C76-00163E06DD4A/logviewer

访问这个页面，点击订阅，点击清除。 切换至网关设置，等待有新日志条数提示。 切换回日志页面

**Comment by a980263316** [comment]
Fixed with commit 5722239234b0eaa92ccccff2f85335a20b76254f
